//
// Created by emmanuel on 15/07/23.
//

#ifndef CONSTRAINTBASEDSIMULATOR_READINPUT_HPP
#define CONSTRAINTBASEDSIMULATOR_READINPUT_HPP


class ReadInput {};


#endif// CONSTRAINTBASEDSIMULATOR_READINPUT_HPP
