#ifndef CONSTRAINTBASEDSIMULATOR_CONSTRAINT_HPP
#define CONSTRAINTBASEDSIMULATOR_CONSTRAINT_HPP

namespace simulator {
struct Constraint {
//TODO
};
}

#endif// CONSTRAINTBASEDSIMULATOR_CONSTRAINT_HPP
