#ifndef CONSTRAINTBASEDSIMULATOR_PARTICLEID_HPP
#define CONSTRAINTBASEDSIMULATOR_PARTICLEID_HPP

#include <string>

namespace simulator {
using ParticleId = std::string;
}

#endif// CONSTRAINTBASEDSIMULATOR_PARTICLEID_HPP
