#ifndef CONSTRAINTBASEDSIMULATOR_SIMULATIONSTATE_HPP
#define CONSTRAINTBASEDSIMULATOR_SIMULATIONSTATE_HPP

namespace simulator {
struct SimulationState {

};
} // simulator

#endif// CONSTRAINTBASEDSIMULATOR_SIMULATIONSTATE_HPP
