#ifndef CONSTRAINTBASEDSIMULATOR_COORDINATE_HPP
#define CONSTRAINTBASEDSIMULATOR_COORDINATE_HPP

namespace input_reader {

using Coordinate = double;

}

#endif// CONSTRAINTBASEDSIMULATOR_COORDINATE_HPP
