name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # - macos-10.15 # doesn't run for free
          - windows-2019
        version:
          - '3.10'
          - 'pypy3.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: pip install -r requirements.txt

      # TODO add unit tests
