name: PyInstaller
on:
  push:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest # doesn't run for free
          - windows-latest
        version:
          - '3.10'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: ${{ matrix.version }}
          spec: 'code/main.py'
          requirements: 'code/requirements.txt'
          upload_exe_with_name: 'ConstraintBasedSimulator-py${{ matrix.version }}-${{ runner.os }}'
          options: --onefile, --name "Constraint Based Simulator", --windowed, 
