name: Tests
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # - macos-10.15 # doesn't run for free
          - windows-2022
        version:
          - '3.10'
          - '3.9'
          - '3.8'
          - 'pypy3.10'
          - 'pypy3.9'
          - 'pypy3.8'
        exclude:
          - os: ubuntu-22.04
            version: 'pypy3.10' # broken PySide6 https://stackoverflow.com/a/76345084/3124150
          - os: ubuntu-22.04
            version: 'pypy3.8' # broken PySide6 https://stackoverflow.com/a/76345084/3124150
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install linux deps
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y libopenblas-dev

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install "jax[cpu]"
          python -m pip install -r requirements.txt -r dev-requirements.txt
      

      - name: Test with pytest
        run: pytest tests/ --doctest-modules --junitxml=junit/test-results-${{ matrix.version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.version }}
          path: junit/test-results-${{ matrix.version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
